# Generated by Django 6.0.3 on 2026-03-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120, verbose_name="Ім'я працівника")),
                ('employee_email', models.EmailField(max_length=254, verbose_name='email працівника')),
                ('request_type', models.CharField(choices=[('laptop', 'Ноутбук'), ('monitor', 'Монітор'), ('mouse', 'Мишка'), ('software', 'Доступ до ПО')], max_length=20, verbose_name='Тип запиту')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Середній'), (3, 'Високий'), (4, 'Терміновий')], verbose_name='Пріорітет')),
                ('description', models.TextField(verbose_name='Опис')),
                ('status', models.IntegerField(choices=[(1, 'Нова'), (2, 'В роботі'), (3, 'Зроблено'), (4, 'Відхилено')], default=1, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
